version: '3'

services:
  app:
    build: ./
    container_name: app
    ports:
      - "5000:5000"
    command: >
      sh -c "python app.py"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=root
    volumes:
      - pg-data:/app
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    networks:
      - mynetwork
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql

networks:
  mynetwork:
    driver: bridge

volumes:
  pg-data:
